# Fehlerbehandlung mit Pandas
Fehler in den Daten selbst beheben

In [24]:
import numpy as np
import pandas as pd

In [25]:
data = pd.read_csv("data/PopulationDataFastFertig.csv", delimiter=',', thousands=",", decimal=".", index_col="Country")

In [26]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

## Probleme mit dem Datenset
- NaN
- N.A.
- Prozentzeichen
- Datentypen (effiziente Typen)

## NaN
isnull(), notnull()

isna(), notna()

In [27]:
data.notna()

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,True,True,True,True,True,True,True,True,True,True
India,True,True,True,True,True,True,True,True,True,True
United States,True,True,True,True,True,True,True,True,True,True
Indonesia,True,True,True,True,True,True,True,True,True,True
Pakistan,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
Montserrat,True,True,True,True,True,False,True,True,True,True
Falkland Islands,True,True,True,True,True,False,True,True,True,True
Niue,True,True,True,True,True,False,True,True,True,True
Tokelau,True,True,True,True,True,False,True,True,True,True
Vatican State,True,True,True,True,True,False,True,True,True,True

In [28]:
data["Migrants"].isna()

Country
China               False
India               False
United States       False
Indonesia           False
Pakistan            False
                    ...
Montserrat           True
Falkland Islands     True
Niue                 True
Tokelau              True
Vatican State        True
Name: Migrants, Length: 235, dtype: bool

In [29]:
x = data["Migrants"].isna()

In [30]:
data["Migrants"][x]

Country
Isle of Man                NaN
Andorra                    NaN
Dominica                   NaN
Cayman Islands             NaN
Bermuda                    NaN
Marshall Islands           NaN
Northern Mariana Islands   NaN
Greenland                  NaN
American Samoa             NaN
Saint Kitts & Nevis        NaN
Faeroe Islands             NaN
Sint Maarten               NaN
Monaco                     NaN
Turks and Caicos           NaN
Saint Martin               NaN
Liechtenstein              NaN
San Marino                 NaN
Gibraltar                  NaN
British Virgin Islands     NaN
Caribbean Netherlands      NaN
Palau                      NaN
Cook Islands               NaN
Anguilla                   NaN
Tuvalu                     NaN
Wallis & Futuna            NaN
Nauru                      NaN
Saint Barthelemy           NaN
Saint Helena               NaN
Saint Pierre & Miquelon    NaN
Montserrat                 NaN
Falkland Islands           NaN
Niue                       NaN
Tokelau                    NaN
Vatican State              NaN
Name: Migrants, dtype: float64

In [31]:
data.isna().value_counts()

Population  YearlyChange  NetChange  Density  LandArea  Migrants  FertRate  MedAge  UrbanPopPct  WorldSharePct
False       False         False      False    False     False     False     False   False        False            201
                                                        True      False     False   False        False             34
Name: count, dtype: int64

In [32]:
data.loc[x, "Migrants"] = 0

In [33]:
data.isna().value_counts()

Population  YearlyChange  NetChange  Density  LandArea  Migrants  FertRate  MedAge  UrbanPopPct  WorldSharePct
False       False         False      False    False     False     False     False   False        False            235
Name: count, dtype: int64

In [34]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,0.0,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,0.0,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,0.0,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,0.0,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00 %

## dropna(), fillna()
dropna(): Wirft alle Zeilen mit NaN Werten weg
fillna(): Füllt NaN Werte mit den vorhergigen/nachfolgenden Werten auf

In [35]:
#data.fillna(method="ffill") veraltet
data.ffill(inplace=True) # ist hier reduntant, weil wir NaN davor schon befüllt haben

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,0.0,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,0.0,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,0.0,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,0.0,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,0.0,N.A.,N.A.,N.A.,0.00 %

## N.A.
Keine automatische Lösung -> manuell
Via. String Replace

In [36]:
data == "N.A."

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,False,False,False,False,False,False,False,False,False,False
India,False,False,False,False,False,False,False,False,False,False
United States,False,False,False,False,False,False,False,False,False,False
Indonesia,False,False,False,False,False,False,False,False,False,False
Pakistan,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
Montserrat,False,False,False,False,False,False,True,True,False,False
Falkland Islands,False,False,False,False,False,False,True,True,False,False
Niue,False,False,False,False,False,False,True,True,False,False
Tokelau,False,False,False,False,False,False,True,True,False,False
Vatican State,False,False,False,False,False,False,True,True,True,False

In [37]:
(data == "N.A.").value_counts()

Population  YearlyChange  NetChange  Density  LandArea  Migrants  FertRate  MedAge  UrbanPopPct  WorldSharePct
False       False         False      False    False     False     False     False   False        False            194
                                                                  True      True    False        False             28
                                                                  False     False   True         False              7
                                                                  True      True    True         False              6
Name: count, dtype: int64

In [38]:
# for col in data.columns:
#     x = data[col] == "N.A."
#     data.loc[x, col] = 0

In [39]:
data = data.replace("N.A.", 0)

In [40]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,0.0,0,0,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,0.0,0,0,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,0.0,0,0,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,0.0,0,0,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,0.0,0,0,0,0.00 %

## Prozentzeichen
Muss mithilfe von String Replace gemacht werden

In [42]:
data["YearlyChange"].replace(" %", "", regex=True)

Country
China               0.39
India               0.99
United States       0.59
Indonesia           1.07
Pakistan            2.00
                    ...
Montserrat          0.06
Falkland Islands    3.05
Niue                0.68
Tokelau             1.27
Vatican State       0.25
Name: YearlyChange, Length: 235, dtype: str

In [43]:
data["YearlyChange"]=data["YearlyChange"].replace(" %", "", regex=True)

In [44]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,0,0,10 %,0.00 %
Falkland Islands,3480,3.05,103,0,12170,0.0,0,0,66 %,0.00 %
Niue,1626,0.68,11,6,260,0.0,0,0,46 %,0.00 %
Tokelau,1357,1.27,17,136,10,0.0,0,0,0 %,0.00 %
Vatican State,801,0.25,2,2003,0,0.0,0,0,0,0.00 %

In [45]:
def fixPct(colName):
    x = data[colName].replace(" %", "", regex=True)
    data[colName]=x

In [46]:
for col in data.columns:
    fixPct(col)

In [47]:
data

,Population,YearlyChange,NetChange,Density,LandArea,Migrants,FertRate,MedAge,UrbanPopPct,WorldSharePct
Country,,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,0,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,0,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,0,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,0,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,0,0,0,0.00

## Datentypen
Bei den vorherigen Änderungen wurden die Typen nicht angepasst

einige sind noch str oder object
ander sind zu groß
-> manuell ändern

In [50]:
data.info()

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Population     235 non-null    int64
 1   YearlyChange   235 non-null    str
 2   NetChange      235 non-null    int64
 3   Density        235 non-null    int64
 4   LandArea       235 non-null    int64
 5   Migrants       235 non-null    float64
 6   FertRate       235 non-null    object
 7   MedAge         235 non-null    object
 8   UrbanPopPct    235 non-null    object
 9   WorldSharePct  235 non-null    str
dtypes: float64(1), int64(4), object(3), str(2)
memory usage: 28.3+ KB

In [51]:
data["Population"] = data["Population"].astype(np.int32)

In [52]:
data.info()

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Population     235 non-null    int32
 1   YearlyChange   235 non-null    str
 2   NetChange      235 non-null    int64
 3   Density        235 non-null    int64
 4   LandArea       235 non-null    int64
 5   Migrants       235 non-null    float64
 6   FertRate       235 non-null    object
 7   MedAge         235 non-null    object
 8   UrbanPopPct    235 non-null    object
 9   WorldSharePct  235 non-null    str
dtypes: float64(1), int32(1), int64(3), object(3), str(2)
memory usage: 27.4+ KB

In [53]:
def fixType(colName, newType):
    data[colName] = data[colName].astype(newType)

In [54]:
fixType("YearlyChange", np.float32)

In [63]:
fixType("NetChange", np.int32)

In [55]:
fixType("Density", np.int16)

In [56]:
fixType("LandArea", np.int32)

In [57]:
fixType("Migrants", np.int32)

In [58]:
fixType("FertRate", np.float32)

In [59]:
fixType("MedAge", np.int8)

In [60]:
fixType("WorldSharePct", np.float32)

In [61]:
fixType("UrbanPopPct", np.int8)

In [64]:
data.info()

<class 'pandas.DataFrame'>
Index: 235 entries, China to Vatican State
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Population     235 non-null    int32
 1   YearlyChange   235 non-null    float32
 2   NetChange      235 non-null    int32
 3   Density        235 non-null    int16
 4   LandArea       235 non-null    int32
 5   Migrants       235 non-null    int32
 6   FertRate       235 non-null    float32
 7   MedAge         235 non-null    int8
 8   UrbanPopPct    235 non-null    int8
 9   WorldSharePct  235 non-null    float32
dtypes: float32(3), int16(1), int32(4), int8(2)
memory usage: 17.3+ KB

In [66]:
1-17.3/27.3

0.36630036630036633

In [67]:
#36,6 Prozent Speicher Ersparnis

Exportieren

In [68]:
data.to_csv("data/PopulationDataFertig.csv")